### ISSUE TITLE
Chat Notifications (May be a new feature)

### ISSUE THREAD

**Issue by kishan3390** [nstosic/toptal-flutter-chat#2]
No any notifications received at both ends for chat between the users either in foreground or background or app in killed state

**Comment by nstosic** [comment]
Hey @kishan3390 thanks for reporting the issue.

As I wrote in the repo's `README` I didn't post my API keys for Firebase (Google Cloud). Are you sure you have set them up properly? Also, you need to write Firebase Cloud function on the instance of Firebase for your project that sends FCM for `messages` collection WRITE trigger . None of the `firebase-functions` code is included in the repo. They are written independently and deployed to Firebase instance.

**Comment by kishan3390** [comment]
@nstosic i have set all the API's properly and chat is working fine but the issue is with the notifications. But i have not done the Firebase Cloud function on the instance of Firebase for your project that sends FCM for messages collection WRITE trigger.

Can you provide some instance or guide me through some links to achieve it

**Comment by ghost** [comment]
hello @nstosic also not getting push notifications and not able to understand if there needs to be further setup after facebook login and firebase

**Comment by kishan3390** [comment]
@sc4224 for receiving push notification you need to create firebase function on firebase console for sending push notification in node js , and deploy that function on firebase

**Comment by nstosic** [comment]
Hey @sc4224 as @kishan3390 wrote, you need to write a Firebase Cloud Function that executes whenever Firestore trigger occurs for onCreate event in `messages` collection of a particular chatroom. Refer to [this link](https://firebase.google.com/docs/functions/firestore-events) for Firestore triggers and refer to [Firebase's own example](https://github.com/firebase/functions-samples/blob/master/fcm-notifications/functions/index.js) for push notification logic.
